### ISSUE TITLE
修改建议

### ISSUE THREAD

**Issue by sempr** [xiaolai/most-common-american-idioms#1]
参照一下 [这个链接](https://stackoverflow.com/a/11804263)

在网页文件中 

`<audio controls>` 改为 `<audio controls preload="none">` 可以避免打开网页就把所有的音频文件给一下子加载完

不然 网页一打开就会疯狂下载大量的不会马上使用的资源

**Comment by xiaolai** [comment]
改了。不过，无论如何这么大的 html 浏览器都有些问题。
