### ISSUE TITLE
HTML页面大部分音频不能播放

### ISSUE THREAD

**Issue by m3home** [xiaolai/most-common-american-idioms#5]
下载了，打开HTML页面，338句之后的所有音频不能播放（播放按钮灰色），链接和音频文件都在，不知道为什么，是浏览器的原因吗
<img width="1014" alt="截屏2024-06-24 18 41 02" src="https://github.com/xiaolai/most-common-american-idioms/assets/6822388/05835ec1-4cc4-4422-a8c8-7382b566c27f">

**Comment by xiaolai** [comment]
我刚才试了一下，没啥问题。只是，html 太大了，怎么弄都有些问题。

**Comment by Lindahe0707** [comment]
Chrome 浏览器的问题,在developer tools里可以看到Chrome设置只能加载1000个音频文件. 建议在terminal用open -a "Google Chrome" --args --max-web-media-player-count=5000打开Chrome, 可以绕过这个限制.

**Comment by xiaolai** [comment]
在 `<audio controls> 里添加了 `preload="none"`。
